[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_vault = "4uWZa2GdP4xDe2kaFyj4emdVvqrTNMnPiKAM6AYShHnj"

[programs.devnet]
solana_vault = "4uWZa2GdP4xDe2kaFyj4emdVvqrTNMnPiKAM6AYShHnj"

[programs.mainnet]
solana_vault = "4uWZa2GdP4xDe2kaFyj4emdVvqrTNMnPiKAM6AYShHnj"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.devnet.solana.com"
clone = [
  { address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" },
]

bind_address = "0.0.0.0"
rpc_port = 8899
websocket_port = 8900
ledger = ".anchor/test-ledger"
log_stdout = false
log_stderr = false
limit_ledger_size = "10000"

[build]
exclude = ["node_modules"]
